Models/ErrorViewModel.cs
using System;

namespace Notes2.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Note.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web.Mvc;

namespace Notes2.Models
{
    public class Note : TimeStampedModel
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        [AllowHtml]
        public string text { get; set; }
    }
}

Models/TimeStampedModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Notes2.Models
{
    public class TimeStampedModel
    {
        public DateTime created { get; set; }
        public DateTime updated { get; set; }
    }
}

Controllers/NotesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Notes2.Models;

namespace Notes2.Controllers
{
    public class NotesController : Controller
    {
        private readonly Notes2Context _context;

        public NotesController(Notes2Context context)
        {
            _context = context;
        }

        // GET: Notes
        public async Task<IActionResult> Index(string searchString)
        {
            var notes = from n in _context.Note select n;

            if (!String.IsNullOrEmpty(searchString))
            {
                notes = notes.Where(n => n.text.Contains(searchString));
            }

            return View(await notes.ToListAsync());
        }

        // GET: Notes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var note = await _context.Note
                .FirstOrDefaultAsync(m => m.ID == id);
            if (note == null)
            {
                return NotFound();
            }

            return View(note);
        }

        // GET: Notes/Create
        public IActionResult Create()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Aplicación de notas";
            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";
            return View();
        }

        // POST: Notes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,text,created,updated")] Note note)
        {
            if (ModelState.IsValid)
            {
                _context.Add(note);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(note);
        }

        // GET: Notes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var note = await _context.Note.FindAsync(id);
            if (note == null)
            {
                return NotFound();
            }
            return View(note);
        }

        // POST: Notes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,text,created,updated")] Note note)
        {
            if (id != note.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(note);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NoteExists(note.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(note);
        }

        // GET: Notes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var note = await _context.Note
                .FirstOrDefaultAsync(m => m.ID == id);
            if (note == null)
            {
                return NotFound();
            }

            return View(note);
        }

        // POST: Notes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var note = await _context.Note.FindAsync(id);
            _context.Note.Remove(note);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NoteExists(int id)
        {
            return _context.Note.Any(e => e.ID == id);
        }
    }
}

Views/Notes/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Aplicación web para la gestión de notas</p>

Views/Notes/Contact.cshtml
@{
    ViewData["Title"] = "Contacto";
}
<h2>@ViewData["Title"]</h2>

<address>
    <strong>Alberto Ramírez Losilla</strong><br />
    <strong>Email: </strong><a href="mailto:alberto.ramirez.losilla@gmail.com">alberto.ramirez.losilla@gmail.com</a><br />
    <strong>Teléfono: </strong>664153757

</address>

Views/Notes/Create.cshtml
@model Notes2.Models.Note


@{
    ViewData["Title"] = "Create";
}



<h2>Create</h2>

<h4>Note</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="text" class="control-label"></label>
                <textarea asp-for="text" class="form-control" id="summernote"></textarea>
                <!--<input asp-for="text" class="form-control" />-->
                <span asp-validation-for="text" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts
{

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script type="text/javascript" src="~/lib/summernote/summernote.js"></script>
    <link href="~/lib/summernote/summernote.css" rel="stylesheet">

    <script>
        $(document).ready(function () {
            $('#summernote').summernote();
        });
    </script>

}

Views/Notes/Delete.cshtml
@model Notes2.Models.Note

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Note</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.text)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.text)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.created)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.created)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.updated)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.updated)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Notes/Details.cshtml
@model Notes2.Models.Note

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Note</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.text)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.text)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.created)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.created)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.updated)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.updated)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Notes/Edit.cshtml
@model Notes2.Models.Note

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Note</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="text" class="control-label"></label>
                <textarea asp-for="text" class="form-control" id="summernote"></textarea>
                <span asp-validation-for="text" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script type="text/javascript" src="~/lib/summernote/summernote.js"></script>
    <link href="~/lib/summernote/summernote.css" rel="stylesheet">

    <script>
        $(document).ready(function () {
            $('#summernote').summernote();
        });
    </script>
}

Views/Notes/Index.cshtml
@model IEnumerable<Notes2.Models.Note>

@{
    ViewData["Title"] = "Index";
}

<form asp-controller="Notes" asp-action="Index">
    <div style="padding-top: 20px;">
        <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="Contenido de la nota" aria-label="Contenido de la nota" aria-describedby="button-addon2" name="searchString">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Buscar</button>
            </div>
        </div>
        <div style="float:right;">
            <button class="btn btn-outline-secondary" type="button" onclick="location.href='@Url.Action("Create","Notes")'">Crear nota</button>
        </div>
    </div>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                Contenido
            </th>
            <th>
                Creado
            </th>
            <th>
                Editado
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.Raw(item.text)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.created)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.updated)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Notas</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment> 

</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Notes" asp-action="Index" class="navbar-brand">Notas</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Notes" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Notes" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - Alberto Ramírez Losilla</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>

    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>